SELECT * FROM PRODUCTOS where VALOR > '1000';

SELECT CLIENTES.CLIENTE, CLIENTES.NOMBRE_CLIENTE, CABEZA_FACTURA.TOTAL FROM CLIENTES
INNER JOIN CABEZA_FACTURA ON CLIENTES.CLIENTE = CABEZA_FACTURA.CLIENTE

SELECT CABEZA_FACTURA.NUMERO, CLIENTES.NOMBRE_CLIENTE, CABEZA_FACTURA.FECHA, PRODUCTOS.NOMBRE_PRODUCTO, DETALLE_FACTURA.CANTIDAD, DETALLE_FACTURA.VALOR FROM CABEZA_FACTURA
INNER JOIN CLIENTES ON CLIENTES.CLIENTE = CABEZA_FACTURA.CLIENTE
INNER JOIN DETALLE_FACTURA ON DETALLE_FACTURA.NUMERO = CABEZA_FACTURA.NUMERO
INNER JOIN PRODUCTOS ON DETALLE_FACTURA.PRODUCTO = PRODUCTOS.PRODUCTO
WHERE FECHA BETWEEN '2005-01-01' AND '2005-03-31'

SELECT COUNT(CANTIDAD) AS CANTIDAD_PRODUCTOS FROM DETALLE_FACTURA

SELECT CLIENTES.CLIENTE, CLIENTES.NOMBRE_CLIENTE FROM CLIENTES 
LEFT OUTER JOIN CABEZA_FACTURA ON CLIENTES.CLIENTE = CABEZA_FACTURA.CLIENTE
LEFT OUTER JOIN DETALLE_FACTURA ON CABEZA_FACTURA.NUMERO = DETALLE_FACTURA.NUMERO
WHERE CANTIDAD IS NULL

SELECT PRODUCTOS.PRODUCTO, PRODUCTOS.NOMBRE_PRODUCTO, SUM(DETALLE_FACTURA.CANTIDAD) AS TOTAL FROM PRODUCTOS
INNER JOIN DETALLE_FACTURA ON DETALLE_FACTURA.PRODUCTO = PRODUCTOS.PRODUCTO
GROUP BY PRODUCTOS.PRODUCTO, PRODUCTOS.NOMBRE_PRODUCTO
ORDER BY TOTAL DESC


INSERT INTO CLIENTES VALUES('1','CARLOS BOGOTA','CALLE 10');
INSERT INTO CLIENTES VALUES('2','JHON ANGEL','CALLE 11');
INSERT INTO CLIENTES VALUES('3','NATALIA PULGARIN','CALLE 12');
INSERT INTO CLIENTES VALUES('4','JAZMIN AREVALO','CALLE 13');

INSERT INTO CABEZA_FACTURA VALUES('1','2005-01-01','1','40000');
INSERT INTO CABEZA_FACTURA VALUES('2','2005-01-10','1','50000');
INSERT INTO CABEZA_FACTURA VALUES('3','2005-01-07','1','30000');
INSERT INTO CABEZA_FACTURA VALUES('4','2005-01-12','2','10000');
INSERT INTO CABEZA_FACTURA VALUES('5','2007-01-12','2','10000');

INSERT INTO DETALLE_FACTURA VALUES('1','1','40','40000');
INSERT INTO DETALLE_FACTURA VALUES('2','1','50','50000');
INSERT INTO DETALLE_FACTURA VALUES('3','2','15','30000');
INSERT INTO DETALLE_FACTURA VALUES('4','2','5','10000');
INSERT INTO DETALLE_FACTURA VALUES('5','2','5','10000');

DELETE FROM DETALLE_FACTURA WHERE NUMERO = '5'

INSERT INTO PRODUCTOS VALUES('1','MANZANA','1000');
INSERT INTO PRODUCTOS VALUES('2','PERA','2000');

